#!/bin/bash
set -e

# Dossier du script (recon_services)
SCRIPT_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

# Racine src pour Python imports
SRC_DIR="$(realpath "$SCRIPT_DIR")/src"

# Ajouter src au PYTHONPATH
export PYTHONPATH="$SRC_DIR:$PYTHONPATH"

# Appel du CLI Python avec tous les arguments
$SCRIPT_DIR/.venv/bin/python "$SRC_DIR/recon.py" "$@"